### ISSUE TITLE
TypeScript Linting 

### ISSUE THREAD

**Issue by lymanlai** [bn-kvh/kvh#2]
#1 
**Is your feature request related to a problem? Please describe.**
Typescript Linting 

**Describe the solution you'd like**
TBD

**Describe alternatives you've considered**
TBD

**Additional context**

- [x] [使用typescript下的项目架构最佳实践](https://juejin.cn/post/6844904048596877320)
- [x]  [Monorepo for all the tooling which enables ESLint to support TypeScript](https://github.com/typescript-eslint/typescript-eslint)
- [x] [代码检查](https://ts.xcatliu.com/engineering/lint) 这个看着搞一波，当做理解细节即可
  - [x] 看完上面的发现得用这个配置 [eslint-config-alloy](https://github.com/AlloyTeam/eslint-config-alloy/blob/master/README.zh-CN.md)
- [x] [在Typescript项目中，如何优雅的使用ESLint和Prettier](https://juejin.cn/post/6844903880006844424)

## 总结

1. 设置 eslint、prettier 及 vscode 自动格式化： https://github.com/bn-kvh/kvh/issues/2#issuecomment-791301434
2. 在项目中 vscode 插件推荐功能？

**Comment by lymanlai** [comment]
## [TS Lint](https://ts.xcatliu.com/engineering/lint) （看看就好，后面会用 alloy 团队的方案替换）
1. 安装开发依赖
```bash
yad -W eslint typescript @typescript-eslint/parser @typescript-eslint/eslint-plugin prettier
```
2. 设置 .eslintrc.js
```js
module.exports = {
    parser: '@typescript-eslint/parser',
    plugins: ['@typescript-eslint'],
    rules: {
        // 禁止使用 var
        'no-var': "error",
        // 优先使用 interface 而不是 type
        '@typescript-eslint/consistent-type-definitions': [
            "error",
            "interface"
        ]
    }
}
```
3. 设置 package.json
```JSON
{
    "scripts": {
        "eslint": "eslint src --ext .ts"
    }
}
```
4. 在 VSCode 中集成 ESLint 检查 .vscode/settings.json
```JSON
{
     "editor.codeActionsOnSave": {
        "source.fixAll.eslint": true
     },
    "eslint.validate": [
        "javascript",
        "typescript"
    ],
    "typescript.tsdk": "node_modules/typescript/lib"
}
```
则会自动修复， 但是很奇怪
`type Foo = {}; ` 会自动修复为 `interface Foo {}`，但是 `var myName = 'Tom'; ` 不会自动修复

5. 使用 Prettier 修复格式错误
创建 `prettier.config.js` 文件
```js
// prettier.config.js or .prettierrc.js
module.exports = {
  // 一行最多 100 字符
  printWidth: 100,
  // 使用 2 个空格缩进
  tabWidth: 2,
  // 不使用缩进符，而使用空格
  useTabs: false,
  // 行尾需要有分号
  semi: false,
  // 使用单引号
  singleQuote: true,
  // 对象的 key 仅在必要时用引号
  quoteProps: "as-needed",
  // jsx 不使用单引号，而使用双引号
  jsxSingleQuote: false,
  // 末尾不需要逗号
  trailingComma: "all",
  // 大括号内的首尾需要空格
  bracketSpacing: true,
  // jsx 标签的反尖括号需要换行
  jsxBracketSameLine: false,
  // 箭头函数，只有一个参数的时候，也需要括号
  arrowParens: "always",
  // 每个文件格式化的范围是文件的全部内容
  rangeStart: 0,
  rangeEnd: Infinity,
  // 不需要写文件开头的 @prettier
  requirePragma: false,
  // 不需要自动在文件开头插入 @prettier
  insertPragma: false,
  // 使用默认的折行标准
  proseWrap: "preserve",
  // 根据显示样式决定 html 要不要折行
  htmlWhitespaceSensitivity: "css",
  // 换行符使用 lf
  endOfLine: "lf",
};
```
.vscode/settings.json
```JSON
{
   "files.eol": "\n",
    "editor.tabSize": 4,
    "editor.formatOnSave": true,
    "editor.defaultFormatter": "esbenp.prettier-vscode",
}
```

**Comment by lymanlai** [comment]
上面白搞了
# [eslint-config-alloy](https://github.com/AlloyTeam/eslint-config-alloy/blob/master/README.zh-CN.md)
[规则示范](https://alloyteam.github.io/eslint-config-alloy/?language=zh-CN&rule=typescript), 可以不看，因为配置好后，prettier 在你写代码的时候，自动帮助你格式化了。
```bash
yad -W eslint typescript @typescript-eslint/parser @typescript-eslint/eslint-plugin eslint-config-alloy
```
## 1. vscode 内搜索并安装 eslint 及 prettier 插件
* [eslint](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint)
* [prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode)

## 2. `.vscode/settings.json`
```JSON
{
  "files.exclude": {
    "packages/*/build": true
  },
  "files.associations": {
    "*.tsconfig.json": "jsonc"
  },
  "eslint.validate": ["javascript", "typescript"],
  "typescript.tsdk": "node_modules/typescript/lib",
  "editor.codeActionsOnSave": {
    "source.fixAll.eslint": true
  },
  "files.eol": "\n",
  "editor.tabSize": 2,
  "editor.formatOnSave": true,
  "editor.defaultFormatter": "esbenp.prettier-vscode"
}
```

## 3. `prettier.config.js`
```js
// .prettierrc.js
module.exports = {
  // 一行最多 120 字符
  printWidth: 120,
  // 使用 2 个空格缩进
  tabWidth: 2,
  // 不使用缩进符，而使用空格
  useTabs: false,
  // 行尾需要有分号
  semi: true,
  // 使用单引号
  singleQuote: true,
  // 对象的 key 仅在必要时用引号
  quoteProps: "as-needed",
  // jsx 不使用单引号，而使用双引号
  jsxSingleQuote: false,
  // 末尾需要有逗号
  trailingComma: "all",
  // 大括号内的首尾需要空格
  bracketSpacing: true,
  // jsx 标签的反尖括号需要换行
  jsxBracketSameLine: false,
  // 箭头函数，只有一个参数的时候，也需要括号
  arrowParens: "always",
  // 每个文件格式化的范围是文件的全部内容
  rangeStart: 0,
  rangeEnd: Infinity,
  // 不需要写文件开头的 @prettier
  requirePragma: false,
  // 不需要自动在文件开头插入 @prettier
  insertPragma: false,
  // 使用默认的折行标准
  proseWrap: "preserve",
  // 根据显示样式决定 html 要不要折行
  htmlWhitespaceSensitivity: "css",
  // vue 文件中的 script 和 style 内不用缩进
  vueIndentScriptAndStyle: false,
  // 换行符使用 lf
  endOfLine: "lf",
  // 格式化嵌入的内容
  embeddedLanguageFormatting: "auto",
};
```

**Comment by lymanlai** [comment]
# module and namespace: 应该是使用 module 的而不是使用 namespace 的吧？

![Screen Shot 2021-03-08 at 3 55 44 PM](https://user-images.githubusercontent.com/105653/110291341-c8265500-8026-11eb-93dc-5b81ccabbdad.png)

* [Re: TypeScript - Namespace? Module?](https://www.tslang.cn/docs/handbook/namespaces-and-modules.html)
* [命名空间和模块](https://www.tslang.cn/docs/handbook/namespaces-and-modules.html)
* [Namespaces and Modules](https://www.typescriptlang.org/docs/handbook/namespaces-and-modules.html)
* [Modules](https://www.typescriptlang.org/docs/handbook/modules.html)
* [Disallow the use of custom TypeScript modules and namespaces (no-namespace)](https://github.com/typescript-eslint/typescript-eslint/blob/v4.16.1/packages/eslint-plugin/docs/rules/no-namespace.md)

**Comment by Gaubee** [comment]
> # module and namespace: 应该是使用 module 的而不是使用 namespace 的吧？
> ![Screen Shot 2021-03-08 at 3 55 44 PM](https://user-images.githubusercontent.com/105653/110291341-c8265500-8026-11eb-93dc-5b81ccabbdad.png)
> 
> * [Re: TypeScript - Namespace? Module?](https://www.tslang.cn/docs/handbook/namespaces-and-modules.html)
> * [命名空间和模块](https://www.tslang.cn/docs/handbook/namespaces-and-modules.html)
> * [Namespaces and Modules](https://www.typescriptlang.org/docs/handbook/namespaces-and-modules.html)
> * [Modules](https://www.typescriptlang.org/docs/handbook/modules.html)
> * [Disallow the use of custom TypeScript modules and namespaces (no-namespace)](https://github.com/typescript-eslint/typescript-eslint/blob/v4.16.1/packages/eslint-plugin/docs/rules/no-namespace.md)

![image](https://user-images.githubusercontent.com/2151644/110292993-fa38b680-8028-11eb-8ce3-073e5a94425b.png)

namespace用来定义类型。不写module，module使用import/export替代。

**Comment by lymanlai** [comment]
## [commitizen + husky 规范git提交信息](https://juejin.cn/post/6844904025868271629)
### 安装依赖
```bash
yad -W commitizen cz-conventional-changelog @commitlint/config-conventional @commitlint/cli
```
### 设置 `package.json`
```JSON
{
  "config":{
    "commitizen":{
        "path":"node_modules/cz-conventional-changelog"
    }
  },
  "scripts":{
    commit:"git-cz"
  }
}
```
### 设置 `.commitlintrc.js`
```js
module.exports = {
  extents:[
      "@commitlint/config-conventional"
  ],
  rules:{
      'body-leading-blank': [1, 'always'],
      'footer-leading-blank': [1, 'always'],
      'header-max-length': [2, 'always', 72],
      'scope-case': [2, 'always', 'lower-case'],
      'subject-case': [
          2,
          'never',
          ['sentence-case', 'start-case', 'pascal-case', 'upper-case']
      ],
      'subject-empty': [2, 'never'],
      'subject-full-stop': [2, 'never', '.'],
      'type-case': [2, 'always', 'lower-case'],
      'type-empty': [2, 'never'],
      'type-enum': [
          2,
          'always',
          [
              'build',
              'chore',
              'ci',
              'docs',
              'feat',
              'fix',
              'improvement',
              'perf',
              'refactor',
              'revert',
              'style',
              'test'
          ]
      ]
  }
}
```

**Comment by lymanlai** [comment]
- [ ] https://github.com/typicode/husky/

当前 npm 版本默认安装 v5， 和大部分教程（v4 版本）的安装方法都有区别

**Comment by lymanlai** [comment]
- [ ] 通过 mrm 做一个通用的开源模板，后续直接一个命令可以生成完整的开源项目

https://github.com/sapegin/mrm

**Comment by lymanlai** [comment]
- [x] husky
- [x] commitlint
- [x] cz-emoji
- [x] pnpm
